# Generated by Django 5.1 on 2024-11-07 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Particula',
            fields=[
                ('id_particula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_particula', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sensor', models.CharField(max_length=100)),
                ('particula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.particula')),
            ],
        ),
        migrations.CreateModel(
            name='ComunaSensor',
            fields=[
                ('id_sensor_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.comuna')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorParticula',
            fields=[
                ('id_sensor_particula', models.AutoField(primary_key=True, serialize=False)),
                ('particula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.particula')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.sensor')),
            ],
        ),
    ]
