# Generated by Django 5.1 on 2024-11-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_registrohorario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='particula',
        ),
    ]
