# Generated by Django 5.1 on 2024-11-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_sensor_particula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroHorario',
        ),
    ]
