# Generated by Django 5.1 on 2024-11-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_registrohorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorparticula',
            name='fecha',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='sensorparticula',
            name='hora',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='sensorparticula',
            name='registros_no_validados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sensorparticula',
            name='registros_preliminares',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sensorparticula',
            name='registros_validados',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
